name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Give execute permissions setup.sh
      run: chmod +x setup.sh

    - name: Set up the scripts
      run: ./setup.sh

    - name: Run tests
      run: pytest
